# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

gui/CMakeFiles/gui.dir/gtk-ui.c.o: gui/gtk-ui.c
gui/CMakeFiles/gui.dir/gtk-ui.c.o: include/rusage.h
gui/CMakeFiles/gui.dir/gtk-ui.c.o: include/ui.h

