# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging

# Include any dependencies generated for this target.
include CMakeFiles/lab.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/lab.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/lab.dir/flags.make

CMakeFiles/lab.dir/main.c.o: CMakeFiles/lab.dir/flags.make
CMakeFiles/lab.dir/main.c.o: main.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/lab.dir/main.c.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lab.dir/main.c.o   -c /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/main.c

CMakeFiles/lab.dir/main.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lab.dir/main.c.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/main.c > CMakeFiles/lab.dir/main.c.i

CMakeFiles/lab.dir/main.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lab.dir/main.c.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/main.c -o CMakeFiles/lab.dir/main.c.s

CMakeFiles/lab.dir/main.c.o.requires:

.PHONY : CMakeFiles/lab.dir/main.c.o.requires

CMakeFiles/lab.dir/main.c.o.provides: CMakeFiles/lab.dir/main.c.o.requires
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/main.c.o.provides.build
.PHONY : CMakeFiles/lab.dir/main.c.o.provides

CMakeFiles/lab.dir/main.c.o.provides.build: CMakeFiles/lab.dir/main.c.o


# Object files for target lab
lab_OBJECTS = \
"CMakeFiles/lab.dir/main.c.o"

# External object files for target lab
lab_EXTERNAL_OBJECTS =

lab: CMakeFiles/lab.dir/main.c.o
lab: CMakeFiles/lab.dir/build.make
lab: cmdline/libcmdlineui.so
lab: librusage.so
lab: CMakeFiles/lab.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking C executable lab"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/lab.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/lab.dir/build: lab

.PHONY : CMakeFiles/lab.dir/build

CMakeFiles/lab.dir/requires: CMakeFiles/lab.dir/main.c.o.requires

.PHONY : CMakeFiles/lab.dir/requires

CMakeFiles/lab.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/lab.dir/cmake_clean.cmake
.PHONY : CMakeFiles/lab.dir/clean

CMakeFiles/lab.dir/depend:
	cd /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/CMakeFiles/lab.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/lab.dir/depend

