# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging

# Include any dependencies generated for this target.
include cmdline/CMakeFiles/cmdlineui.dir/depend.make

# Include the progress variables for this target.
include cmdline/CMakeFiles/cmdlineui.dir/progress.make

# Include the compile flags for this target's objects.
include cmdline/CMakeFiles/cmdlineui.dir/flags.make

cmdline/CMakeFiles/cmdlineui.dir/ui.c.o: cmdline/CMakeFiles/cmdlineui.dir/flags.make
cmdline/CMakeFiles/cmdlineui.dir/ui.c.o: cmdline/ui.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object cmdline/CMakeFiles/cmdlineui.dir/ui.c.o"
	cd /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline && /usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/cmdlineui.dir/ui.c.o   -c /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline/ui.c

cmdline/CMakeFiles/cmdlineui.dir/ui.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/cmdlineui.dir/ui.c.i"
	cd /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline && /usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline/ui.c > CMakeFiles/cmdlineui.dir/ui.c.i

cmdline/CMakeFiles/cmdlineui.dir/ui.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/cmdlineui.dir/ui.c.s"
	cd /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline && /usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline/ui.c -o CMakeFiles/cmdlineui.dir/ui.c.s

cmdline/CMakeFiles/cmdlineui.dir/ui.c.o.requires:

.PHONY : cmdline/CMakeFiles/cmdlineui.dir/ui.c.o.requires

cmdline/CMakeFiles/cmdlineui.dir/ui.c.o.provides: cmdline/CMakeFiles/cmdlineui.dir/ui.c.o.requires
	$(MAKE) -f cmdline/CMakeFiles/cmdlineui.dir/build.make cmdline/CMakeFiles/cmdlineui.dir/ui.c.o.provides.build
.PHONY : cmdline/CMakeFiles/cmdlineui.dir/ui.c.o.provides

cmdline/CMakeFiles/cmdlineui.dir/ui.c.o.provides.build: cmdline/CMakeFiles/cmdlineui.dir/ui.c.o


# Object files for target cmdlineui
cmdlineui_OBJECTS = \
"CMakeFiles/cmdlineui.dir/ui.c.o"

# External object files for target cmdlineui
cmdlineui_EXTERNAL_OBJECTS =

cmdline/libcmdlineui.so: cmdline/CMakeFiles/cmdlineui.dir/ui.c.o
cmdline/libcmdlineui.so: cmdline/CMakeFiles/cmdlineui.dir/build.make
cmdline/libcmdlineui.so: cmdline/CMakeFiles/cmdlineui.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking C shared library libcmdlineui.so"
	cd /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/cmdlineui.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
cmdline/CMakeFiles/cmdlineui.dir/build: cmdline/libcmdlineui.so

.PHONY : cmdline/CMakeFiles/cmdlineui.dir/build

cmdline/CMakeFiles/cmdlineui.dir/requires: cmdline/CMakeFiles/cmdlineui.dir/ui.c.o.requires

.PHONY : cmdline/CMakeFiles/cmdlineui.dir/requires

cmdline/CMakeFiles/cmdlineui.dir/clean:
	cd /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline && $(CMAKE_COMMAND) -P CMakeFiles/cmdlineui.dir/cmake_clean.cmake
.PHONY : cmdline/CMakeFiles/cmdlineui.dir/clean

cmdline/CMakeFiles/cmdlineui.dir/depend:
	cd /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline /users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/cmdline/CMakeFiles/cmdlineui.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : cmdline/CMakeFiles/cmdlineui.dir/depend

