# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# compile C with /usr/bin/cc
C_FLAGS = -fPIC  

C_DEFINES = -Drusage_EXPORTS

C_INCLUDES = -I/users/labnet/st7/jtb240/8894-Labs/1/lab3/3-paging/include 

